### ISSUE TITLE
Default output volume is very low.

### ISSUE THREAD

**Issue by lpil** [AVUIs/cantor-dust#4]

**Comment by berkan** [comment]
yes i think so too. the 'dust' gets really small (those values we sonify
directly are amplitudes), so the volume gets lower and lower on higher
iterations.

haven't had a chance to think about how to sensibly and automatically
adjust it to decent audible levels. maybe via a gibberish ugen to that
automatically does some gain manipulations.

as a quick fix, we can make the volume controls take larger steps and
magnitudes (the maximum amp gain is 10 atm, so the small values just get
multiplied by 10 at the most -- which is not much).
