### ISSUE TITLE
Separate playback positions make it difficult to align cycles

### ISSUE THREAD

**Issue by lpil** [AVUIs/cantor-dust#5]
One thing I previously enjoyed was making beat-y patterns. I'm finding this much harder to do now. It would be nice if there was a way to snap cycles together.

**Comment by berkan** [comment]
this sounds really cool. can you record a session with the pre-gibberish
version so that i know how it sounds and whether there is something not
right with this version that stops it..

**Comment by lpil** [comment]
If you can find the video from the performance there's a little snippet of me doing it at the end of it. :)

**Comment by berkan** [comment]
i've tried to recreate your set from the performance:

```
http://avuis.github.io/cantor-dust/#louis-performance
```

http://avuis.github.io/cantor-dust/#STATE:%5B%7B%22iterations%22:7,%22pattern%22:%5B0.8300000000000003,0.5,0.3799999999999999,0.47%5D,%22phase%22:890%7D,%7B%22iterations%22:7,%22pattern%22:%5B0.8900000000000003,0,0.2899999999999998,0%5D,%22phase%22:895.25%7D,%7B%22iterations%22:7,%22pattern%22:%5B0,0,0,0%5D,%22phase%22:886.125%7D,%7B%22iterations%22:7,%22pattern%22:%5B0.9200000000000004,0.43999999999999995,0.8000000000000003,0.31999999999999984%5D,%22phase%22:889.625%7D,%7B%22iterations%22:7,%22pattern%22:%5B0.8600000000000003,0,0,0.2599999999999998%5D,%22phase%22:889.625%7D,%7B%22iterations%22:7,%22pattern%22:%5B0,0.1399999999999998,0,0.5%5D,%22phase%22:887.875%7D,%7B%22iterations%22:7,%22pattern%22:%5B0.09,0.2299999999999998,0.10999999999999979,0.31999999999999984%5D,%22phase%22:889.625%7D,%7B%22iterations%22:7,%22pattern%22:%5B0.5,0.6200000000000001,0.31999999999999984,0.43999999999999995%5D,%22phase%22:891.375%7D%5D

the "background" of it sounds similar, but i can't get your beat pattern
when i play with the 5th synth in the way you do. also - that synth is very
quiet - were you also doing something with the volume during the
performance?

i've committed a new version for you: now you can press Shift-P, and all
the synths will be synced.

in general, for half of the commands, pressing the Shift key will apply it
too all the synths, and pressing the Alt key will apply the command to all
but the focused synth.

b.

**Comment by berkan** [comment]
(really cool performance and sound by the way -- so wish i could have been
there)

**Comment by lpil** [comment]
Thanks, I had so much fun! In theory I'm forming a laptop band off the back of it, but I've not dedicated any time to making stuff for it. :(

**Comment by berkan** [comment]
that's interesting! i've been thinking about the same thing as well (only
using instruments that are custom-built, two of which we've done together)
-- fancy having a jamming/hacking/brainstorming session?
